export const cities = [
  { label: "Agadir", value: "Agadir" },
  { label: "Al Hoceima", value: "Al Hoceima" },
  { label: "Azemmour", value: "Azemmour" },
  { label: "Azrou", value: "Azrou" },
  { label: "Beni Mellal", value: "Beni Mellal" },
  { label: "Boujdour", value: "Boujdour" },
  { label: "Bouznika", value: "Bouznika" },
  { label: "Casablanca", value: "Casablanca" },
  { label: "Chefchaouen", value: "Chefchaouen" },
  { label: "El Jadida", value: "El Jadida" },
  { label: "Essaouira", value: "Essaouira" },
  { label: "Fes", value: "Fes" },
  { label: "Guelmim", value: "Guelmim" },
  { label: "Ifrane", value: "Ifrane" },
  { label: "Kenitra", value: "Kenitra" },
  { label: "Khenifra", value: "Khenifra" },
  { label: "Khouribga", value: "Khouribga" },
  { label: "Laayoune", value: "Laayoune" },
  { label: "Larache", value: "Larache" },
  { label: "Marrakech", value: "Marrakech" },
  { label: "Meknes", value: "Meknes" },
  { label: "Mohammedia", value: "Mohammedia" },
  { label: "Nador", value: "Nador" },
  { label: "Ouarzazate", value: "Ouarzazate" },
  { label: "Ouezzane", value: "Ouezzane" },
  { label: "Oujda", value: "Oujda" },
  { label: "Rabat", value: "Rabat" },
  { label: "Safi", value: "Safi" },
  { label: "Salé", value: "Sale" },
  { label: "Tangier", value: "Tangier" },
  { label: "Taza", value: "Taza" },
  { label: "Tétouan", value: "Tetouan" },
  { label: "Zagora", value: "Zagora" },
];
